In [10]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler

In [2]:
heart_df = pd.read_csv("1-heart.csv")
heart_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
X = heart_df.drop(columns=["target"]) 
y = heart_df["target"]
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X,y, test_size = 0.2, random_state = 42)

In [5]:
# Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [6]:
# k= 3
knn_model = KNeighborsClassifier(n_neighbors=3)
knn_model.fit(X_train_scaled, y_train)
y_pred = knn_model.predict(X_test_scaled)

print("Accuracy Score", accuracy_score(y_test, y_pred))
print("Precision Score", precision_score(y_test, y_pred))
print("Recall Score", recall_score(y_test, y_pred))

Accuracy Score 0.8524590163934426
Precision Score 0.9259259259259259
Recall Score 0.78125

In [7]:
# k= 5
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)
y_pred = knn_model.predict(X_test_scaled)

print("Accuracy Score", accuracy_score(y_test, y_pred))
print("Precision Score", precision_score(y_test, y_pred))
print("Recall Score", recall_score(y_test, y_pred))

Accuracy Score 0.9016393442622951
Precision Score 0.9333333333333333
Recall Score 0.875

In [8]:
# k= 7, best till now
knn_model = KNeighborsClassifier(n_neighbors=7)
knn_model.fit(X_train_scaled, y_train)
y_pred = knn_model.predict(X_test_scaled)

print("Accuracy Score", accuracy_score(y_test, y_pred))
print("Precision Score", precision_score(y_test, y_pred))
print("Recall Score", recall_score(y_test, y_pred))

Accuracy Score 0.9180327868852459
Precision Score 0.9354838709677419
Recall Score 0.90625

In [13]:
# Cross Validation for hyperparameters usng GridSearchCV
classifier = KNeighborsClassifier()
params_grid = {"n_neighbors":[3,5,7,9]}
classifierCV = GridSearchCV(
    classifier,
    params_grid,
    cv=5
)

classifierCV.fit(X_train_scaled, y_train)
y_pred = classifierCV.predict(X_test_scaled)

res = pd.DataFrame(classifierCV.cv_results_)
print(res[["param_n_neighbors","mean_test_score"]])

print(classifierCV.best_params_)

   param_n_neighbors  mean_test_score
0                  3         0.805782
1                  5         0.814116
2                  7         0.801616
3                  9         0.801786
{'n_neighbors': 5}

In [21]:
# pipeline
from sklearn.pipeline import Pipeline

X_train, X_test, y_train, y_test = train_test_split(
    X,y, test_size = 0.2, random_state = 42)

pipeline = Pipeline([
    ('scaler',StandardScaler()), 
    ('knn',KNeighborsClassifier(n_neighbors=5))
])

params_grid = {"knn__n_neighbors":[3,5,7,9]}
classifierCV = GridSearchCV(
    pipeline,
    params_grid,
    cv=5,
    scoring='recall'
)


classifierCV.fit(X_train, y_train)
y_pred = classifierCV.predict(X_test)

print("Accuracy Score", accuracy_score(y_test, y_pred))
print("Precision Score", precision_score(y_test, y_pred))
print("Recall Score", recall_score(y_test, y_pred))

print(classifierCV.best_params_)

Accuracy Score 0.9180327868852459
Precision Score 0.9354838709677419
Recall Score 0.90625
{'knn__n_neighbors': 7}