In [34]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import seaborn as sns
import numpy as np

In [7]:
df = sns.load_dataset("titanic")

In [8]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [9]:
features = ["pclass", "sex", "age", "fare", "embarked"]
target = ["survived"]

In [10]:
#handle missing value
imp_median = SimpleImputer(strategy="median")
df[["age"]] = imp_median.fit_transform(df[["age"]])

imp_freq = SimpleImputer(strategy="most_frequent")
df[["embarked"]] = imp_freq.fit_transform(df[["embarked"]])

In [11]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [12]:
# encode
le = LabelEncoder()
df["sex"] = le.fit_transform(df["sex"])
df["embarked"] =le.fit_transform(df["embarked"])

In [13]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,Third,man,True,NaN,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,0,First,woman,False,C,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,2,Third,woman,False,NaN,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,2,First,woman,False,C,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,2,Third,man,True,NaN,Southampton,no,True

In [14]:
X = df[features]
y = df["survived"]

In [15]:
X.head()

   pclass  sex   age     fare  embarked
0       3    1  22.0   7.2500         2
1       1    0  38.0  71.2833         0
2       3    0  26.0   7.9250         2
3       1    0  35.0  53.1000         2
4       3    1  35.0   8.0500         2

In [16]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64

In [17]:
X_train, X_test, y_train , y_test = train_test_split(
    X,y,test_size=0.3, random_state=42)

In [18]:
rf = RandomForestClassifier(oob_score=True, n_estimators=501, max_depth=4)

rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=4, n_estimators=501, oob_score=True)

In [19]:
y_pred = rf.predict(X_test)

print("OOB score:", (rf.oob_score_)*100,"%")
print("Accuracy:", accuracy_score(y_test, y_pred)*100,"%")

OOB score: 82.6645264847512 %
Accuracy: 81.71641791044776 %

In [24]:
#Bagging Classiifer (Decision tree)
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier

base_model = DecisionTreeClassifier()

bc = BaggingClassifier(
    base_model,
    n_estimators=201
)

bc.fit(X_train, y_train)

y_pred = bc.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7723880597014925

In [30]:
#Bagging Classiifer (LogisticRegression)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier

base_model = LogisticRegression()

bc = BaggingClassifier(
    base_model,
    n_estimators=201
)

bc.fit(X_train, y_train)

y_pred = bc.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7947761194029851

In [35]:
#Bagging Classiifer (LinearRegression)

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import BaggingRegressor

base_model = LinearRegression()

bc = BaggingRegressor(
    base_model,
    n_estimators=201
)

bc.fit(X_train, y_train)

y_pred = bc.predict(X_test)

print("mse:", mean_squared_error(y_test, y_pred))

mse: 0.1386809589266391

In [37]:
#Bagging Classiifer (SVM Classifier)

from sklearn.svm import SVR
from sklearn.ensemble import BaggingRegressor

base_model = SVR()

bc = BaggingRegressor(
    base_model,
    n_estimators=201
)

bc.fit(X_train, y_train)

y_pred = bc.predict(X_test)

print("mse:", mean_squared_error(y_test, y_pred))

mse: 0.2446605216560068